### ISSUE TITLE
TSynC2_Nun Corpus

### ISSUE THREAD

**Issue by cnamuangtoun** [PyThaiNLP/G2P#1]
Hi, I am looking to get the TSynC2_Nun corpus. However I downloaded it from https://www.aiforthai.in.th/corpus.php, but the zip file is corrupted and I was only able to retrieve the wavs folder and nothing else. Could you give me some information on how to get the TSynC2 corpus? Thanks!

**Comment by wannaphong** [comment]
You can download from Mirror https://nlpforthai.com/tasks/speech-synthesis/

**Comment by cnamuangtoun** [comment]
Mirror link works, thank you!
